In [20]:
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from graphviz import Source
from IPython.display import SVG
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support

In [14]:
particles_train = pd.read_csv('data/training.csv')

display(particles_train.head())
display(particles_train.columns)
display(particles_train["Label"].unique())

TrackP  TrackNDoFSubdetector2  BremDLLbeElectron  MuonLooseFlag  \
0  74791.156263                   15.0           0.232275            1.0   
1   2738.489989                   15.0          -0.357748            0.0   
2   2161.409908                   17.0        -999.000000            0.0   
3  15277.730490                   20.0          -0.638984            0.0   
4   7563.700195                   19.0          -0.638962            0.0   

   FlagSpd   SpdE  EcalDLLbeElectron     DLLmuon  RICHpFlagElectron  \
0      1.0    3.2          -2.505719    6.604153                1.0   
1      1.0    3.2           1.864351    0.263651                1.0   
2      0.0 -999.0        -999.000000 -999.000000                0.0   
3      1.0    3.2          -2.533918   -8.724949                1.0   
4      1.0    3.2          -2.087146   -7.060422                1.0   

   EcalDLLbeMuon  ...  TrackNDoF  RICHpFlagMuon  RICH_DLLbeKaon  \
0       1.929960  ...       28.0            1.0       -7.213300   
1      -2.061959  ...       32.0            1.0       -0.324317   
2    -999.000000  ...       27.0            0.0     -999.000000   
3      -3.253981  ...       36.0            1.0      -35.202221   
4      -0.995816  ...       33.0            1.0       25.084287   

   RICH_DLLbeElectron        HcalE  MuonFlag  FlagMuon        PrsE  \
0           -0.280200  5586.589846       1.0       1.0   10.422315   
1            1.707283    -0.000007       0.0       1.0   43.334935   
2         -999.000000  -999.000000       0.0       0.0 -999.000000   
3          -14.742319  4482.803707       0.0       1.0    2.194175   
4          -10.272412  5107.554680       0.0       1.0    0.000015   

   RICH_DLLbeMuon  RICH_DLLbeProton  
0   -2.081143e-07        -24.824400  
1    2.771583e+00         -0.648017  
2   -9.990000e+02       -999.000000  
3   -3.070819e+00        -29.291519  
4   -5.373712e+00         23.653087  

[5 rows x 50 columns]

Index(['TrackP', 'TrackNDoFSubdetector2', 'BremDLLbeElectron', 'MuonLooseFlag',
       'FlagSpd', 'SpdE', 'EcalDLLbeElectron', 'DLLmuon', 'RICHpFlagElectron',
       'EcalDLLbeMuon', 'TrackQualitySubdetector2', 'FlagPrs', 'DLLelectron',
       'DLLkaon', 'EcalE', 'TrackQualityPerNDoF', 'DLLproton',
       'PrsDLLbeElectron', 'FlagRICH1', 'MuonLLbeBCK', 'FlagHcal',
       'EcalShowerLongitudinalParameter', 'Calo2dFitQuality', 'TrackPt',
       'TrackDistanceToZ', 'RICHpFlagPion', 'HcalDLLbeElectron',
       'Calo3dFitQuality', 'FlagEcal', 'MuonLLbeMuon', 'TrackNDoFSubdetector1',
       'RICHpFlagProton', 'RICHpFlagKaon', 'GhostProbability',
       'TrackQualitySubdetector1', 'Label', 'RICH_DLLbeBCK', 'FlagRICH2',
       'FlagBrem', 'HcalDLLbeMuon', 'TrackNDoF', 'RICHpFlagMuon',
       'RICH_DLLbeKaon', 'RICH_DLLbeElectron', 'HcalE', 'MuonFlag', 'FlagMuon',
       'PrsE', 'RICH_DLLbeMuon', 'RICH_DLLbeProton'],
      dtype='object')

array(['Muon', 'Ghost', 'Pion', 'Proton', 'Kaon', 'Electron'],
      dtype=object)

In [17]:
# Train Test Split

feature_cols = [x for x in particles_train.columns if x != "Label"]
feature_set = particles_train[feature_cols]
labels = particles_train["Label"]
X_train, X_test, y_train, y_test = train_test_split(feature_set, labels, test_size=0.25, random_state=69)

In [25]:

for i in range(2, 9):
    print("Creating Decision tree of depth", i)
    treeclf = DecisionTreeClassifier(max_depth=i, random_state=4)
    treeclf.fit(X_train, y_train)

    dot = tree.export_graphviz(treeclf, out_file=None,
    feature_names=feature_cols,
    class_names=["Muon", "Ghost", "Pion", "Proton", "Kaon", "Electron"], filled=True)

    y_pred = treeclf.predict(X_test)
    p,r,f,s = precision_recall_fscore_support(y_test, y_pred)
    print(p)
    print(r)
    print(f)
    print(s)

    graph = Source(dot)
    svg = SVG(graph.pipe(format='svg'))
    #display(svg)

    graph = Source(dot, format="png")
    #graph.render(filename="depth" + str(i), directory="./charts", view=False)

Creating Decision tree of depth 2


/usr/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


[0.83904883 0.63971088 0.         0.82586225 0.24249525 0.        ]
[0.78143773 0.1495656  0.         0.79911678 0.93969638 0.        ]
[0.80921919 0.2424467  0.         0.81226941 0.38550757 0.        ]
[49940 50299 50387 49591 49997 49786]
Creating Decision tree of depth 3


/usr/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


[0.8268407  0.69999052 0.         0.82586225 0.28921614 0.        ]
[0.81942331 0.73375216 0.         0.79911678 0.86653199 0.        ]
[0.82311529 0.71647383 0.         0.81226941 0.43368453 0.        ]
[49940 50299 50387 49591 49997 49786]
Creating Decision tree of depth 4
[0.85841995 0.69609375 0.46468289 0.90604042 0.54746778 0.42613302]
[0.80372447 0.74399093 0.76458213 0.78459801 0.78766726 0.01454224]
[0.83017229 0.71924581 0.57804986 0.84095748 0.6459608  0.0281247 ]
[49940 50299 50387 49591 49997 49786]
Creating Decision tree of depth 5
[0.84656467 0.70357075 0.49803778 0.91412178 0.54823138 0.50201487]
[0.8220865  0.73253941 0.26949412 0.78709847 0.80412825 0.56300968]
[0.83414604 0.71776291 0.34973987 0.84586796 0.65196909 0.53076566]
[49940 50299 50387 49591 49997 49786]
Creating Decision tree of depth 6
[0.87005258 0.70976995 0.5536112  0.92037148 0.579644   0.56899694]
[0.8050861  0.74772858 0.44892532 0.80736424 0.7900674  0.55192223]
[0.83630955 0.72825498 0.49580256 0.